- name: Create direcotory for repo
  file: path={{ project_root }} state=directory
- name: Transfer backend source directory to project root directory
  synchronize:
    src: backend/
    dest: "{{ project_root }}/backend"
    archive: no
    recursive: yes
    times: yes
    delete: yes
    use_ssh_args: yes
    verify_host: yes
    rsync_opts:
      - "--exclude=backend/node_modules"
# - name: Transfer frontend source directory to project root directory
#   synchronize:
#     src: frontend/
#     dest: "{{ project_root }}/frontend"
#     archive: no
#     recursive: yes
#     times: yes
#     delete: yes
#     use_ssh_args: yes
#     verify_host: yes
#     rsync_opts:
#       - "--exclude=frontend/node_modules"
